### ISSUE TITLE
Support for Komodo 9.3

### ISSUE THREAD

**Issue by 0x6d6c** [Komodo/komodo-editorconfig#1]
Hi,
it seems this add-on is no longer compatible with Komodo 9.3?
I use now Komodo Edit 9.3 for Linux, have installed editorconfig on KE 9.2 and it has worked fine.
Best regards,
ML

**Comment by mitchell-as** [comment]
Hi, EditorConfig support is built into Komodo now. There is no need for a separate add-on.
