### ISSUE TITLE
Not compatible with komodo edit 9.3

### ISSUE THREAD

**Issue by ADmad** [Komodo/komodo-editorconfig#2]
Trying to install "EditorConfig" addon through komodo edit 9.3's package installer it gives error: "This package is not compatible with your version of Komodo"

**Comment by Defman21** [comment]
You don't have to install it, this package is a part of 9.3 release.

**Comment by ADmad** [comment]
Woops, thanks. Might be a good idea to not list it in the add-ons list then.
